---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# datardis

<!-- badges: start -->
<!-- badges: end -->

The goal of datardis is to provide datasets from the Doctor Who TV series.
Three datasets are available :  
**episodes** : list of all episodes from the revived era (2005-present)  
**directors** : list of directors   
**writers** : list of writers

## Installation

You can download and install the package from CRAN:
```{r CRAN, echo=TRUE, eval=FALSE, warning=FALSE, message=FALSE}
install.packages("datardis")
```


You can install the development version from [GitHub](https://github.com/) with:
```{r dev version, echo=TRUE, eval=FALSE, warning=FALSE, message=FALSE}
devtools::install_github("KittJonathan/datardis")
```

## Examples

```{r examples, message=FALSE, warning=FALSE}

## Load packages
library(datardis)
library(tidyverse)

## Find maximum number of UK viewers (in millions)
max(episodes$uk_viewers, na.rm = TRUE)

## Find who wrote the most episodes
writers %>%
     count(writer) %>%
     arrange(desc(n)) %>%
     head(5)

## Find who directed the most episodes
directors %>%
     count(director) %>%
     arrange(desc(n)) %>%
     head(5)

```
